# ================================
# Dockerfile.dev — Ambiente de desenvolvimento com Air
# ================================
FROM golang:1.25-alpine

RUN apk add --no-cache mysql-client


WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@latest

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
